### ISSUE TITLE
Buildroot set up for BBB

### ISSUE THREAD

**Issue by Vaidehisalway** [cu-ecen-5013/final-project-Vaidehisalway#1]
In progress

**Comment by Vaidehisalway** [comment]
DoD: Successful generation of linux image sdcard.img for BB

**Comment by Vaidehisalway** [comment]
Status update: Successful buildroot set up and (sdcard.img) image generated for BBB.

**Comment by Vaidehisalway** [comment]
link to closed issue: https://github.com/cu-ecen-5013/final-project-Vaidehisalway.git

**Comment by steveantony5** [comment]
@Vaidehisalway  Please edit the first comment and move the dod there
Refer: https://docs.google.com/document/d/1nHiCKOrHSQBuZVDpSXKqPFwV5W3lHyvE4heCGnz7ghw/edit referencing step 3.f
