### ISSUE TITLE
UART driver for Beaglebone Black

### ISSUE THREAD

**Issue by Vaidehisalway** [cu-ecen-5013/final-project-Vaidehisalway#2]
UART setup on Beaglebone black for testing the communication and transfer of data between Arduino and BBB using UART .

DoD: Able to receive sensor data from Arduino via UART

BLOCKER: NONE AS OF NOW.

**Comment by Vaidehisalway** [comment]
Status: UART patch added for BBB

**Comment by steveantony5** [comment]
@Vaidehisalway The first comment should explain what is this task for
and dod should explain how will you verify it.

Not everthing should be under dod

**Comment by Vaidehisalway** [comment]
> @Vaidehisalway The first comment should explain what is this task for
> and dod should explain how will you verify it.
> 
> Not everthing should be under dod

**Comment by Vaidehisalway** [comment]
STATUS: UART driver written, testing in process

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: Successfully added UART Patch to enable UART ports on Beaglebone Black. https://github.com/cu-ecen-5013/final-project-Vaidehisalway/blob/master/base_external/patches/linux/uart.patch, 65d9f9fa5f42d16d67ef6ea34691c6e0f0d99ee8

Implemented a UART driver on Beaglebone Black and successfully completed loop back testing, received sensor values from arduino via UART https://github.com/cu-ecen-5013/final-project-Kushagra42/tree/master/UART_Communication
571347940f6ebe3bd5fa12c84c738a15d9469f22
