### ISSUE TITLE
SPRINT 3

### ISSUE THREAD

**Issue by Vaidehisalway** [cu-ecen-5013/final-project-Vaidehisalway#3]
TO DO: Synchronize the data reception from Raspi, Arduino via UART and SPI Temperature sensor on BBB. Create Load and unload scripts for the UART and SPI modules.

DoD: Able to receive the synchronized data from all 3 sensors (in a given time interval ) and display on the terminal.

BLOCKER: Awaiting data from SPI sensor https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi1_s0.patch

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: Completed  Integration of all the code snippets i.e UART interface with arduino board emulating Raspi, UART interface with Arduino, I2C interface with Beaglebone. Successfully tested the synchronization on target Beaglebone black.

1)UART interface for beaglebone with arduino and raspi  test code
https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/6e89c78cd643cea8f84dca58283686599ca350d1
commit : 6e89c78cd643cea8f84dca58283686599ca350d1

2)simplifed and cleaned code for UART  implementation for raspi, arduino and I2C implementation on beaglebone (copied the contributed code  by kushagra) 
https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/f140ce89ead09f7fc3b7db62fb19d29168f3bf9d#diff-5a5a7488766f65bb9a6a4f942b4359b5
commit : f140ce89ead09f7fc3b7db62fb19d29168f3bf9d


BLOCKER: BLOCKER RESOLVED, Received Temperature data from Raspi
https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Temperature_i2c.c

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: Implemented the Auto recovery system which can tolerate run time faults such as wire  disconnection or sensor disconnection, the program keeps on running and restarts taking sensor value once connections are made.
Implemented Hard Real time system, where irrespective of the time taken by the sensors to take the reading and send to Beaglebone (as long as this delay from all the sensors is below the set timing interval), the sleep duration/delay for Beaglebone will vary dynamically. Example: if set time interval is 1 sec and sensor takes 200 ms so the sleep time will be 800 ms and if sensor takes 600 ms, the sleep time will change to 400 ms, So it always maintains that readings taken are at the set interval.

1)Added  hardreal time library files and made changes in the integrated code
https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/14a9868bbe94dd75bda7e25f78099f75b999361d#diff-176d1b44f6b28bb281a4b76e7ff32114
commit : 14a9868bbe94dd75bda7e25f78099f75b999361d

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: SPI blocker is removed as my project partner decided to move to I2C based sensor, after consultation.
https://github.com/cu-ecen-5013/final-project-Kushagra42/tree/7e79fe7d21640629b9b48316d3840c0f0767ca39/I2C_Data_BB

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: received raw temperature  values from Raspi 
https://github.com/cu-ecen-5013/final-project-Vaidehisalway

**Comment by steveantony5** [comment]
@Vaidehisalway  Please fix the linking error for the link  https://github.com/cu-ecen-5013/final-project-Vaidehisalway/blob/master/base_external/patches/linux/spi1_s0.patch

**Comment by steveantony5** [comment]
@Vaidehisalway  Is this the code (https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/All_Data_Sync.c ) you checked in for this work?
