### ISSUE TITLE
SPRINT 3 FINAL

### ISSUE THREAD

**Issue by Vaidehisalway** [cu-ecen-5013/final-project-Vaidehisalway#4]
TO DO: Implement two of the sensor data comparison modes allowing user to manually select the modes according to their application.

MODES are : 1) Reference Mode
                      2) Statistic Mode

Final integration of all the applications with testing and verification.

DoD: User will be able to choose between different modes of sensor data comparison, based on the selection , the correct sensor data will be sent to the server using socket application. The code should run without any errors and give the desired output.

2 User modes:
https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/5fa2941b8abe4474d7ede9a63b506d0fdfd5130f#diff-0318e9b850d49f120372223e38838c32
commit : 5fa2941b8abe4474d7ede9a63b506d0fdfd5130f

**Comment by Vaidehisalway** [comment]
STATUS UPDATE: Received raw data from Raspi over UART and temperature data from arduino via UART and from i2c sensor on BB. 
Integration of the code is done where I implemented 2 user modes i.e statistic and reference mode for analyzing correct sensor data. Testing was done, code runs without any errrors.
User is able to choose from different user modes and send accurate results over the socket to the server.

User modes:
cu-ecen-5013/final-project-Kushagra42@5fa2941#diff-0318e9b850d49f120372223e38838c32
commit : 5fa2941b8abe4474d7ede9a63b506d0fdfd5130f

FINAL CODE: All the libraries written for implementing hard real time were included and the functions from these libraries were used in the main code "main.c"
https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/99ade2e63f2fa1ef76f231685940dfcd0bfb8bbc#diff-4678f4e8ba5add5fd715e68197538558
commit : 99ade2e63f2fa1ef76f231685940dfcd0bfb8bbc

**Comment by steveantony5** [comment]
@Vaidehisalway  Can you please add a commit link for me to look at the code you checked in for sprint 3?
